version: '3.8'
services:
  ub-backend:
    image: ${IMAGE_TAG:-ghcr.io/melowetty/ub-backend:stable}
    healthcheck:
      test: ["/workspace/health-check"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 768M
    environment:
      THC_PORT: 8080
      THC_PATH: '/actuator/health'
    env_file: ./.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
    ports:
      - published: 8080
        target: 8080
        protocol: tcp
        mode: ingress
    networks:
      - internal
      - logging

  db:
    image: postgres:17.6-alpine
    deploy:
      restart_policy:
        condition: on-failure
    env_file: ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - published: 5436
        target: 5432
        protocol: tcp
        mode: ingress
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  db:
    name: ub-backend_db

networks:
  internal:
    driver: overlay
    attachable: true
  logging:
    external: true