logging:
  config: classpath:logback-prod.xml

server:
  port: 8080

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 1
            threadsInheritContextClassLoaderOfInitializingThread: true

security:
  bot:
    username: ${SECURITY_BOT_USERNAME}
    password: ${SECURITY_BOT_PASSWORD}

integrations:
  yandex-disk:
    token: ${YANDEX_DISK_OAUTH_TOKEN}
  telegram:
    link: ${TELEGRAM_BOT_LINK}
    token: ${TELEGRAM_BOT_TOKEN}

debug: false