database:
  host: localhost
  port: 5432
  name: university-and-business-bot-backend
  username: postgres
  password: postgres

security:
  bot:
    username: test
    password: test

integrations:
  yandex-disk:
    token: ${YANDEX_DISK_OAUTH_TOKEN:test}
    base-url: https://cloud-api.yandex.net/v1/disk/resources
  telegram:
    link: ${TELEGRAM_BOT_LINK:https://t.me/university_and_business_bot}
    token: ${TELEGRAM_BOT_TOKEN:test}

spring:
  application:
    name: university-and-business-bot-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: ${database.username}
    password: ${database.password}
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}

  liquibase:
    enabled: false

  security:
    user:
      name: ${security.bot.username}
      password: ${security.bot.password}
      roles:
        - ADMIN

debug: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
server:
  port: 8082