database:
  host: localhost
  port: 5432
  name: university-and-business-bot-backend
  username: postgres
  password: postgres

security:
  bot:
    username: test
    password: test

spring:
  application:
    name: university-and-business-bot-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: ${database.username}
    password: ${database.password}
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}

  liquibase:
    enabled: false

  security:
    user:
      name: ${security.bot.username}
      password: ${security.bot.password}
      roles:
        - ADMIN