name: Backend CI

on:
  pull_request:
    branches: [master, dev]
    paths:
      - 'src/main/**'
      - 'src/test/**'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle.properties'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - 'Dockerfile'
      - 'docker-compose*.yml'
      - 'scripts/**'
      - '.github/workflows/**'

env:
  IMAGE_NAME: ub-backend

jobs:
  build:
    name: "Build project"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-deps-ci-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-deps-ci-

      - name: Build project with build cache
        run: |
          chmod +x gradlew
          CI=true ./gradlew clean build -x test --build-cache

  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Restore Cache Gradle dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-deps-ci-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-deps-ci-

      - name: Run tests with build cache
        run: |
          ./gradlew check --build-cache